ALTER TABLE applications ALTER COLUMN id DROP DEFAULT;
ALTER TABLE projects ALTER COLUMN id DROP DEFAULT;
ALTER TABLE organizations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE permissions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE identities ALTER COLUMN id DROP DEFAULT;
ALTER TABLE login_methods ALTER COLUMN id DROP DEFAULT;
ALTER TABLE user_accounts ALTER COLUMN id DROP DEFAULT;