

###

POST localhost:3000/admin/projects
Content-Type: application/json

{
  "org_id": "019bbe2a-0d7c-76d1-96ef-77abe31b0763",
  "name": "project-3"
}

###

POST localhost:3000/admin/applications
Content-Type: application/json

{
  "project_id": "019bbe32-9846-7fb0-a938-d277ab19a168",
  "redirect_uris": ["my_redirect_uri_1"],
  "org_id": "019bbe2a-0d7c-76d1-96ef-77abe31b0763",
  "name": "application-1"
}

###

POST localhost:3000/auth/register
Content-Type: application/json

{
  "identifier": "a@a.com",
  "method_type": "email",
  "password": "12345",
  "client_id": "019bbe3b-5287-7d02-9f06-ac0ae428ca4e",
  "profile": {}
}

###

PUT localhost:3000/admin/applications/a/scopes
Content-Type: application/json

{
  "application_scopes": []
}