POST localhost:3000/admin/organizations
Content-Type: application/json

{
  "name": "company"
}

###

POST localhost:3000/admin/projects
Content-Type: application/json

{
  "org_id": "019baa12-f1fd-7b86-830b-6de536e434c3",
  "name": "project-1"
}

###

POST localhost:3000/admin/applications
Content-Type: application/json

{
  "project_id": "aaaac4f4-e41a-41ce-ba42-98f495e07de7",
  "redirect_uris": [],
  "org_id": "a89ade62-feb6-4ce7-8b0a-493ed26c17d9",
  "name": "project-1"
}

###

POST localhost:3000/auth/register
Content-Type: application/json

{
  "identifier": "a@a.com",
  "method_type": "email",
  "password": "12345",
  "client_id": "a89ade62-feb6-4ce7-8b0a-493ed26c17d9",
  "profile": {}
}